from typing import Protocol, Any

class MainWindowProtocol(Protocol):
    action_adjust_global_font: Any
    action_adjust_global_size: Any
    action_ai_character: Any
    action_ai_chat: Any
    action_ai_continuation: Any
    action_ai_impression: Any
    action_ai_proofread: Any
    action_ai_settings: Any
    action_ai_timeline: Any
    action_ai_world: Any
    action_auto_format: Any
    action_autosave_settings: Any
    action_exit: Any
    action_export: Any
    action_export_backup: Any
    action_export_dataset: Any
    action_find: Any
    action_global_search: Any
    action_import: Any
    action_lint: Any
    action_load_latest_project: Any
    action_load_project: Any
    action_load_temp_project: Any
    action_new_book: Any
    action_replace: Any
    action_restore_backup: Any
    action_save_project: Any
    action_save_project_as: Any
    action_show_outline: Any
    action_show_write: Any
    action_show_writing_log: Any
    action_snapshot_manager: Any
    action_storage_path_settings: Any
    action_theme_celadon: Any
    action_theme_default: Any
    action_theme_forest: Any
    action_theme_green: Any
    action_theme_polar: Any
    action_theme_sepia: Any
    action_toggle_focus: Any
    action_word_count_settings: Any
    arrow_icon_color: Any
    btn_add_card: Any
    btn_bold: Any
    btn_clear_progress: Any
    btn_clear_trash: Any
    btn_delete_permanently: Any
    btn_ellipsis: Any
    btn_emdash: Any
    btn_italic: Any
    btn_punc_colon: Any
    btn_punc_comma_pause: Any
    btn_punc_exclamation: Any
    btn_punc_question: Any
    btn_punc_quote_double: Any
    btn_punc_quote_single: Any
    btn_punc_section: Any
    btn_punc_semicolon: Any
    btn_restore: Any
    btn_save_scene_info: Any
    btn_set_project_target: Any
    btn_set_target: Any
    btn_strike: Any
    btn_toggle_left: Any
    btn_toggle_right: Any
    btn_toggle_view_mode: Any
    btn_trash: Any
    btn_typewriter: Any
    card_tree: Any
    center_stack: Any
    close: Any
    closeEvent: Any
    combo_font: Any
    combo_size: Any
    current_theme: Any
    editor: Any
    file_icon_color: Any
    findChildren: Any
    find_replace_bar: Any
    folder_icon_color: Any
    last_left_width: Any
    last_right_width: Any
    lbl_current_file: Any
    lbl_focus_banner: Any
    lbl_left_title: Any
    lbl_progress: Any
    lbl_project_logline: Any
    lbl_project_progress: Any
    lbl_project_title: Any
    lbl_right_title: Any
    lbl_word_count: Any
    left_bottom_bar: Any
    left_panel: Any
    left_widget: Any
    outline_view: Any
    progress_bar: Any
    project_progress_bar: Any
    right_panel: Any
    right_widget: Any
    scale_actions: Any
    scale_factor: Any
    scene_info_location_edit: Any
    scene_info_pov_edit: Any
    scene_info_summary_edit: Any
    scene_tab_index: Any
    setStyleSheet: Any
    setWindowTitle: Any
    signal_edit_logline: Any
    signal_edit_project_title: Any
    signal_tree_context_menu: Any
    splitter: Any
    statusBar: Any
    tabs: Any
    toggle_focus_mode: Any
    trash_icon_color: Any
    trash_list_widget: Any
    tree_widget: Any
    winId: Any
    writing_log_dashboard: Any
